api_platform:
    title: 'API Outillages'
    description: 'Gestion des données outillages, de la demande de création à son suivi'
    version: '1.5.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    formats:
        json:
            mime_types: ['application/json']
            
        jsonld:
            mime_types: ['application/ld+json']

        html:
            mime_types: ['text/html']
    defaults:
        pagination_enabled: false
